"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/Button"

export default function PrivacyPage() {
  const [lang, setLang] = useState<"it" | "en">("it")

  useEffect(() => {
    if (typeof window !== "undefined") {
      if (navigator.language.startsWith("en")) {
        setLang("en")
      }
    }
  }, [])

  return (
    <main className="min-h-screen bg-primary p-6 md:p-12 pb-24">
      <div className="max-w-4xl mx-auto space-y-8">
        <div className="flex flex-col sm:flex-row justify-between items-center gap-4 bg-white border-[4px] border-black p-4 shadow-brutal">
          <Link href="/">
            <Button variant="outline" className="font-bold">← Home</Button>
          </Link>
          <div className="flex gap-2">
            <Button 
              variant={lang === "it" ? "primary" : "outline"} 
              onClick={() => setLang("it")}
            >
              IT
            </Button>
            <Button 
              variant={lang === "en" ? "primary" : "outline"} 
              onClick={() => setLang("en")}
            >
              EN
            </Button>
          </div>
        </div>

        <div className="bg-white border-[4px] border-black p-6 md:p-10 shadow-brutal space-y-8">
          <h1 className="text-3xl md:text-5xl font-black uppercase text-center bg-yellow-300 inline-block px-4 py-2 border-[2px] border-black -rotate-1 mb-6">
            Privacy & Cookie Policy
          </h1>

          {lang === "it" ? (
            <div className="space-y-6 text-lg font-medium text-gray-800">
              <p>Ultimo aggiornamento: Giugno 2026</p>
              
              <section className="space-y-2">
                <h2 className="text-2xl font-bold uppercase border-b-[3px] border-black inline-block">Titolare del Trattamento</h2>
                <p><strong>Daniele Sarcina</strong> (Email: daniele.sarcina@gmail.com)</p>
              </section>

              <section className="space-y-2">
                <h2 className="text-2xl font-bold uppercase border-b-[3px] border-black inline-block">Dati Raccolti</h2>
                <p>Nome, Cognome, Email e immagine del profilo trasmessi tramite Google OAuth.</p>
              </section>

              <section className="space-y-2">
                <h2 className="text-2xl font-bold uppercase border-b-[3px] border-black inline-block">Finalità</h2>
                <p>Esclusivamente l'autenticazione, la personalizzazione della dashboard e la gestione delle scommesse della lega.</p>
              </section>

              <section className="space-y-2">
                <h2 className="text-2xl font-bold uppercase border-b-[3px] border-black inline-block">Cookie Utilizzati</h2>
                <p>Unicamente cookie tecnici di prima parte generati da NextAuth per il mantenimento della sessione di login. Nessun cookie di profilazione o terze parti (no Google Analytics, no pixel, no pubblicità).</p>
              </section>
            </div>
          ) : (
            <div className="space-y-6 text-lg font-medium text-gray-800">
              <p>Last updated: June 2026</p>
              
              <section className="space-y-2">
                <h2 className="text-2xl font-bold uppercase border-b-[3px] border-black inline-block">Data Controller</h2>
                <p><strong>Daniele Sarcina</strong> (Email: daniele.sarcina@gmail.com)</p>
              </section>

              <section className="space-y-2">
                <h2 className="text-2xl font-bold uppercase border-b-[3px] border-black inline-block">Data Collected</h2>
                <p>First name, last name, email, and profile picture from Google OAuth.</p>
              </section>

              <section className="space-y-2">
                <h2 className="text-2xl font-bold uppercase border-b-[3px] border-black inline-block">Purposes</h2>
                <p>Strictly for authentication, dashboard personalization, and league bet management.</p>
              </section>

              <section className="space-y-2">
                <h2 className="text-2xl font-bold uppercase border-b-[3px] border-black inline-block">Cookies Used</h2>
                <p>Only first-party technical cookies generated by NextAuth for session maintenance. No profiling or third-party cookies.</p>
              </section>
            </div>
          )}
        </div>
      </div>
    </main>
  )
}
